Repository zetonteam/zeton_django, pull requests merged in 2024-09, with the labels that each got.

#162 GET 'students/<id>' tests, tests refactor
  README.md
  tests/common.py
  tests/test_current_user.py
  tests/test_students.py
  tests/test_token_auth.py
Labels: python

#163 Remove pyyaml dependency
  poetry.lock
  pyproject.toml
Labels: dependencies, python

#171 Add points tests
  README.md
  fixtures/points.json
  tests/conftest.py
  tests/test_point.py
Labels: python

#174 Updated README.md and separate 'students/' views
  README.md
  users/urls.py
  users/views.py
Labels: enhancement, python

#176 Add students PATCH tests
  README.md
  tests/common.py
  tests/test_point.py
  tests/test_students.py
Labels: python

#177 Implement tests for "/api/students/<int:id>/prizes" GET
  README.md
  tests/test_prizes.py
Labels: python

#179 Implement tests for "/api/students/<int:id>/prize/<int:id>" GET
  README.md
  tests/test_prizes.py
  users/views.py
Labels: bug, python

#185 Change tests groups
  tests/test_current_user.py
  tests/test_points.py
  tests/test_prizes.py
  tests/test_students.py
  tests/test_token_auth.py
Labels: python

#192 Fix token-auth endpoint doc
  README.md
Labels: documentation

#186 Single prize patch tests
  README.md
  tests/test_prizes.py
Labels: python, tests, ready for merge

#187 Prizes post tests
  README.md
  tests/common.py
  tests/test_prizes.py
Labels: python, tests, ready for merge

#180 Students tasks get tests
  README.md
  tests/test_tasks.py
Labels: python, tests, ready for approve

#193 "/api/students" POST implementation and tests
  README.md
  tests/test_students.py
  users/serializers.py
  users/views.py
Labels: python

#196 Uniform trailing slashes
  README.md
  tests/test_current_user.py
  tests/test_prizes.py
  tests/test_students.py
  tests/test_tasks.py
  tests/test_token_auth.py
  users/urls.py
Labels: bug, python

#197 Use HTTP status 201 for POST
  README.md
  tests/test_prizes.py
  users/views.py
Labels: bug, python

#183 Implement tests for "students/<int:student_id>/points" POST
  README.md
  tests/test_points.py
Labels: python, tests, waiting for review

#203 Fix 'students/<int:student_id>/task/<int:task_id>/' GET tests row
  README.md
Labels: bug, documentation

#206 Fix fixtures, formatting, pre-commit
  .pre-commit-config.yaml
  fixtures/caregivers.json
  fixtures/points.json
  fixtures/prizes.json
  fixtures/roles.json
  fixtures/students.json
  fixtures/tasks.json
  fixtures/users.json
  tests/test_students.py
Labels: enhancement

#204 Implement tests for "/api/students/<int:student_id>/task/<int:task_id>/" PATCH
  README.md
  tests/test_tasks.py
Labels: enhancement, python

#208 Add full command on how to run tests
  README.md
Labels: documentation

#210 Add student_id to get task response
  tests/test_tasks.py
  users/serializers.py
Labels: python, waiting for review

#205 Implement tests for DELETE method for task and prize
  README.md
  tests/common.py
  tests/test_prizes.py
  tests/test_tasks.py
Labels: enhancement, python
